version: '3'
services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cofin"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - main-network


  bezkoder-api:
    depends_on:
      - mysqldb
    build: ./bezkoder-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8000:8000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend


  web:
    build:
      context: ./cofin-msa-user-frontend2
      dockerfile: Dockerfile
    image: swlee9087/cofin-user
    container_name: cofin-user
    command: sh -c "dockerize -wait tcp://host.docker.internal:3306 -timeout 20s && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/backend/
    expose:
      - "8000"
    depends_on:
      - backend
networks:
  main-network:
    driver: bridge